src/objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>Parent_territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Territories</relationshipLabel>
        <relationshipName>Child_territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TerritoryTriggerHandler.cls
/**
 * Created by Danil on 07.04.2018.
 */

public with sharing class TerritoryTriggerHandler {


    private void updateTerritoryShareForEachTerritory(List<Territory__c> listWithTerritories) {
        List<TerritoryShare__c> listToUpdate = [SELECT Id FROM TerritoryShare__c
                                                WHERE ParentId__c IN
                                                    (SELECT Parent_territory__c
                                                     FROM Territory__c
                                                     WHERE Id IN :listWithTerritories)
        ];
        update listToUpdate;
    }

    private void deleteTerritoryShareForEachTerritory(List<Territory__c> listWithTerritories) {
        List<TerritoryShare__c> listToDelete = [SELECT Id FROM TerritoryShare__c
                                                WHERE ParentId__c IN :listWithTerritories
        ];
        delete listToDelete;
    }


    public void onAfterInsert(List<Territory__c> newList) {
        updateTerritoryShareForEachTerritory(newList);
    }

    public void onAfterUpdate(List<Territory__c> newList) {
        updateTerritoryShareForEachTerritory(newList);
    }

    public void onBeforeUpdate(List<Territory__c> oldList) {
        deleteTerritoryShareForEachTerritory(oldList);
    }

    public void onBeforeDelete(List<Territory__c> oldList) {
        deleteTerritoryShareForEachTerritory(oldList);
    }
}